const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./index.js']

const doc = {
    info: {
        version: "1.0.1",
        title: "José Neto Thesis API",
        description: `Documentation automatically generated by the <b>swagger.autogen</b> module.
                    <p> José Neto </p>`

    },
    host: "localhost:5431",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [{
        "name": "Measurements",
        "description": "Endpoints to upload, read or delete measurement data"
    }
    ]
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})